driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: <%= ENV['CHEF_VERSION'] || "current" %>

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: centos-6
    driver:
      image: centos:6
      platform: rhel
    pid_one_command: /sbin/init
  - name: centos-7
    driver:
      image: centos:7
      platform: rhel
      pid_one_command: /usr/lib/systemd/systemd
  - name: fedora-latest
    driver:
      image: dokken/fedora-latest
      pid_one_command: /usr/lib/systemd/systemd
  - name: debian-7
    driver:
      image: dokken/debian-7
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
